version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d8:39:d0:0a:48:36:ac:9a:d6:e2:a8:8b:84:03:08:8f"
      - checkout
      - run:
          name: deploy
          command: |
            gem install bundler:1.17.0
            bundle install
            ./deploy.sh

workflows:
    open-api-doc:
      jobs:
        - deploy:
            branches:
              only:
                - master