version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            gem install bundler:1.17.0
            bundle install
            ./deploy.sh

workflows:
    open-api-doc:
      jobs:
        - deploy:
            filters:
                branches:
                  only:
                    - master